# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: First
    steps:
    - bash: echo First
  - job: Second
    steps:
    - bash: Second
- stage: DevDeploy
  jobs:
  - job: Dev
    steps:
    - bash: echo Dev
- stage: QADeploy
  jobs:
  - job: QA
    steps:
    - bash: echo QA
- stage: ProdDeploy
  jobs:
  - job: Prod
    steps:
    - bash: echo Prod




