# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)   

stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Do Build"
- stage: Dev
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
       deploy:
         steps:
           - script: echo deploy to dev
- stage: QA
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
       deploy:
         steps:
           - script: echo deploy to QA
       



# steps:
# - script: echo $(operatingSystem)
#   displayName: 'Run a one-line script'
# stages:
# - stage: Build
#   jobs:
#   - job: First
#     steps:
#     - bash: echo $(operatingSystem)
  # - job: Second
  #   steps:
  #   - bash: echo Second
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: Dev
#     steps:
#     - bash: echo Dev
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QA
#     steps:
#     - bash: echo QA
# - stage: ProdDeploy
#   jobs:
#   - job: Prod
#     steps:
#     - bash: echo Prod




